name: 'Build'

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup python'
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Install Poetry'
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: 'Determine Artifact Name'
        id: determine_artifact_name
        run: |
          if [[ "${{ github.ref }}" == refs/heads/feature/* ]]; then
            echo "artifact_name=artifact-snapshot.zip" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/development ]]; then
            echo "artifact_name=artifact-rc.zip" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/master ]]; then
            echo "artifact_name=artifact-release.zip" >> $GITHUB_ENV
          else
            echo "artifact_name=artifact.zip" >> $GITHUB_ENV
          fi

      - name: 'Create Package'
        id: 'create_package'
        run: |
          poetry --version
          poetry run python --version
          poetry install --no-interaction --no-ansi
          poetry build
          poetry run pip install --upgrade --target package dist/*.whl
          cd package && zip -r ../${{ env.artifact_name }} . -x '*.pyc'

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Upload to S3'
        run: aws s3 cp ${{ env.artifact_name }} s3://${{ secrets.AWS_BUCKET }}/
