name: 'Deploy'


env:
  AWS_BUCKET: "arn:aws:s3:::pickem-api"
  AWS_LAMBDA: "arn:aws:s3:::pickem-api"

on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download S3 Object Name Artifact'
        uses: actions/download-artifact@v3
        with:
          name: s3-object-name

      - name: 'Read S3 Object Name'
        id: read_s3_object_name
        run: |
          s3_object_name=$(cat s3_object_name.txt)
          echo "s3_object_name=${s3_object_name}" >> $GITHUB_ENV


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::881413588329:role/Pickem_GithubActions
          aws-region: us-east-1

      - name: 'Update Lambda Function with S3 Object Name'
        run: |
          aws lambda update-function-code \
            --function-name=$AWS_LAMBDA \
            --s3-bucket=$AWS_BUCKET \
            --s3-key=${{ env.s3_object_name }} \
            --cli-read-timeout 60 \
            --cli-connect-timeout 60
